language: node_js

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libprotobuf-dev

node_js:
  - "0.10"
  - "0.12"
  - "4.1.1"

compiler:
  - gcc

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
